export const clinics = [
  {
    id: 1,
    slug: "clinique-al-azhar-zeralda",
    name: "Clinique Al Azhar",
    location: "Zeralda, Algiers",
    rating: 4.9,
    specialties: ["General Practice", "Cardiology"],
    image: "/images/clinic-1.jpg",
    phone: "+213 21 32 45 67",
    email: "contact@alazhar-zeralda.dz",
    address: "12 Avenue des Palmiers, Zeralda, 16000 Algiers",
    hours: "Sat - Thu: 8:00 AM - 6:00 PM",
    description:
      "Clinique Al Azhar is a premier healthcare facility in Zeralda, offering comprehensive medical services with state-of-the-art equipment and experienced healthcare professionals dedicated to patient care.",
    services: [
      "General Consultations",
      "Cardiology",
      "Laboratory Tests",
      "ECG & Cardiac Monitoring",
      "Health Check-ups",
    ],
  },
  {
    id: 2,
    slug: "clinique-en-nahda-la-cote",
    name: "Clinique En-Nahda",
    location: "La Cote, Algiers",
    rating: 4.8,
    specialties: ["Pediatrics", "Family Medicine"],
    image: "/images/clinic-2.jpg",
    phone: "+213 21 54 78 90",
    email: "contact@ennahda-lacote.dz",
    address: "45 Boulevard de la Cote, 16000 Algiers",
    hours: "Sat - Thu: 8:00 AM - 7:00 PM",
    description:
      "Clinique En-Nahda specializes in pediatric and family medicine, providing compassionate care for patients of all ages in a warm, welcoming environment along the beautiful coast.",
    services: [
      "Pediatric Care",
      "Family Medicine",
      "Vaccinations",
      "Child Development",
      "Prenatal Care",
    ],
  },
  {
    id: 3,
    slug: "clinique-les-sources-birmandreis",
    name: "Clinique Les Sources",
    location: "Birmandreis, Algiers",
    rating: 4.8,
    specialties: ["Gynecology", "Obstetrics"],
    image: "/images/clinic-3.jpg",
    phone: "+213 21 67 89 12",
    email: "contact@lessources-birmandreis.dz",
    address: "78 Rue des Sources, Birmandreis, 16000 Algiers",
    hours: "Sat - Thu: 8:30 AM - 5:30 PM",
    description:
      "Clinique Les Sources offers comprehensive gynecology and obstetrics services, supporting women at every stage of life with professionalism and care.",
    services: [
      "Gynecological Consultations",
      "Pregnancy Monitoring",
      "Ultrasounds",
      "Deliveries",
      "Family Planning",
    ],
  },
  {
    id: 4,
    slug: "clinique-du-val-el-biar",
    name: "Clinique du Val",
    location: "El Biar, Algiers",
    rating: 4.9,
    specialties: ["Ophthalmology", "ENT"],
    image: "/images/clinic-4.jpg",
    phone: "+213 21 92 34 56",
    email: "contact@duval-elbiar.dz",
    address: "23 Avenue du Val, El Biar, 16000 Algiers",
    hours: "Sat - Thu: 8:30 AM - 5:30 PM",
    description:
      "Clinique du Val is dedicated to eye and ear health, offering comprehensive examinations and treatments with cutting-edge equipment in the prestigious El Biar neighborhood.",
    services: [
      "Eye Examinations",
      "Vision Correction",
      "Cataract Surgery",
      "ENT Consultations",
      "Hearing Tests",
    ],
  },
  {
    id: 5,
    slug: "centre-medical-ibn-sina-oran",
    name: "Centre Medical Ibn Sina",
    location: "Oran, Algeria",
    rating: 4.7,
    specialties: ["Internal Medicine", "Diabetes Care"],
    image: "/images/clinic-5.jpg",
    phone: "+213 41 32 18 90",
    email: "contact@ibnsina-oran.dz",
    address: "78 Boulevard de l'ALN, Oran, 31000",
    hours: "Sat - Thu: 8:00 AM - 6:00 PM",
    description:
      "Centre Medical Ibn Sina focuses on preventive medicine and chronic disease management, helping patients maintain optimal health through personalized care plans.",
    services: [
      "Internal Medicine",
      "Diabetes Management",
      "Health Screenings",
      "Chronic Disease Care",
      "Nutritional Counseling",
    ],
  },
  {
    id: 6,
    slug: "clinique-errahma-setif",
    name: "Clinique Errahma",
    location: "Setif, Algeria",
    rating: 4.6,
    specialties: ["Emergency", "Trauma Care"],
    image: "/images/clinic-6.jpg",
    phone: "+213 36 84 12 56",
    email: "contact@errahma-setif.dz",
    address: "89 Boulevard 8 Mai 1945, Setif, 19000",
    hours: "Open 24/7",
    description:
      "Clinique Errahma provides round-the-clock emergency and urgent care services, ensuring quick access to quality medical attention when you need it most.",
    services: [
      "Emergency Care",
      "Trauma Care",
      "Minor Surgery",
      "X-Ray Services",
      "Laboratory Tests",
    ],
  },
];
